-- Create Customer Table
CREATE TABLE Customer (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255),
    Email VARCHAR2(255),
    Password VARCHAR2(255),
    Phone VARCHAR2(50),
    Address VARCHAR2(500)
);

-- Create Supplier Table
CREATE TABLE Supplier (
    SupplierID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255),
    Email VARCHAR2(255),
    Password VARCHAR2(255),
    Phone VARCHAR2(50)
);

-- Create Product Table (FIXED "SIZE" RESERVED WORD)
CREATE TABLE Product (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR2(255),
    "SIZE" NUMBER, 
    Description VARCHAR2(1000),
    Price NUMBER(10, 2)
);

-- Create Warehouse Table
CREATE TABLE Warehouse (
    WarehouseID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TotalCapacity NUMBER,
    Location VARCHAR2(255),
    FreeSpace NUMBER
);

-- Create Cart Table
CREATE TABLE Cart (
    CartID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER,
    CONSTRAINT fk_cart_customer FOREIGN KEY (CustomerID) 
        REFERENCES Customer(CustomerID)
);

-- Create CartItem Table (FIXED PK)
CREATE TABLE CartItem (
    CartItemID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CartID NUMBER,
    ProductID NUMBER,
    Quantity NUMBER,
    CONSTRAINT fk_cartitem_cart FOREIGN KEY (CartID) 
        REFERENCES Cart(CartID),
    CONSTRAINT fk_cartitem_product FOREIGN KEY (ProductID) 
        REFERENCES Product(ProductID)
);

CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER,
    Status VARCHAR2(50),
    OrderDate DATE,
    DeliveredDate DATE,
    CONSTRAINT fk_orders_customer FOREIGN KEY (CustomerID) 
        REFERENCES Customer(CustomerID)
);

-- 4. Recreate the OrderItem table
CREATE TABLE OrderItem (
    OrderItemID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER,
    ProductID NUMBER,
    Quantity NUMBER,
    UnitPrice NUMBER(10, 2),
    CONSTRAINT fk_orderitem_orders FOREIGN KEY (OrderID) 
        REFERENCES Orders(OrderID),
    CONSTRAINT fk_orderitem_product FOREIGN KEY (ProductID) 
        REFERENCES Product(ProductID)
);

-- Create Inventory Table (FIXED PK)
CREATE TABLE Inventory (
    InventoryID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WarehouseID NUMBER,
    ProductID NUMBER,
    Quantity NUMBER,
    CONSTRAINT fk_inventory_warehouse FOREIGN KEY (WarehouseID) 
        REFERENCES Warehouse(WarehouseID),
    CONSTRAINT fk_inventory_product FOREIGN KEY (ProductID) 
        REFERENCES Product(ProductID)
);

-- Create Supply Table (FIXED PK)
CREATE TABLE Supply (
    SupplyID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SupplierID NUMBER,
    ProductID NUMBER,
    Cost NUMBER(10, 2),
    CONSTRAINT fk_supply_supplier FOREIGN KEY (SupplierID) 
        REFERENCES Supplier(SupplierID),
    CONSTRAINT fk_supply_product FOREIGN KEY (ProductID) 
        REFERENCES Product(ProductID)
);