CREATE TABLE Account (
    AccountID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email VARCHAR2(255) UNIQUE NOT NULL,
    Password VARCHAR2(255) NOT NULL,
    UserRole VARCHAR2(50) NOT NULL
);

CREATE TABLE Customer (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255),
    Phone VARCHAR2(50),
    Address VARCHAR2(500),
    AccountID NUMBER UNIQUE,
    CONSTRAINT fk_customer_account FOREIGN KEY (AccountID) 
        REFERENCES Account(AccountID)
);

CREATE TABLE Supplier (
    SupplierID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255),
    Phone VARCHAR2(50),
    AccountID NUMBER UNIQUE,
    CONSTRAINT fk_supplier_account FOREIGN KEY (AccountID) 
        REFERENCES Account(AccountID)
);

CREATE TABLE Product (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR2(255),
    "SIZE" NUMBER, 
    Description VARCHAR2(1000),
    Price NUMBER(10, 2)
);

CREATE TABLE Warehouse (
    WarehouseID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TotalCapacity NUMBER,
    Location VARCHAR2(255),
    FreeSpace NUMBER
);

CREATE TABLE Cart (
    CartID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER,
    CONSTRAINT fk_cart_customer FOREIGN KEY (CustomerID) 
        REFERENCES Customer(CustomerID)
);

CREATE TABLE CartItem (
    CartItemID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CartID NUMBER,
    ProductID NUMBER,
    Quantity NUMBER,
    CONSTRAINT fk_cartitem_cart FOREIGN KEY (CartID) 
        REFERENCES Cart(CartID),
    CONSTRAINT fk_cartitem_product FOREIGN KEY (ProductID) 
        REFERENCES Product(ProductID)
);

CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER,
    Status VARCHAR2(50),
    OrderDate DATE,
    DeliveredDate DATE,
    CONSTRAINT fk_orders_customer FOREIGN KEY (CustomerID) 
        REFERENCES Customer(CustomerID)
);

CREATE TABLE OrderItem (
    OrderItemID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER,
    ProductID NUMBER,
    Quantity NUMBER,
    UnitPrice NUMBER(10, 2),
    CONSTRAINT fk_orderitem_orders FOREIGN KEY (OrderID) 
        REFERENCES Orders(OrderID),
    CONSTRAINT fk_orderitem_product FOREIGN KEY (ProductID) 
        REFERENCES Product(ProductID)
);

CREATE TABLE Inventory (
    InventoryID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WarehouseID NUMBER,
    ProductID NUMBER,
    Quantity NUMBER,
    CONSTRAINT fk_inventory_warehouse FOREIGN KEY (WarehouseID) 
        REFERENCES Warehouse(WarehouseID),
    CONSTRAINT fk_inventory_product FOREIGN KEY (ProductID) 
        REFERENCES Product(ProductID)
);

CREATE TABLE Supply (
    SupplyID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SupplierID NUMBER,
    ProductID NUMBER,
    Cost NUMBER(10, 2),
    CONSTRAINT fk_supply_supplier FOREIGN KEY (SupplierID) 
        REFERENCES Supplier(SupplierID),
    CONSTRAINT fk_supply_product FOREIGN KEY (ProductID) 
        REFERENCES Product(ProductID)
);